apiVersion: v1
kind: Secret
metadata:
  name: admin-api-secret
  namespace: admin-api
type: Opaque
stringData:
  JWT_SECRET: "12345678901234567890123456789012"
  MONGODB_URI: "mongodb://admin:tripro123@103.165.144.81:27017/admin_db?authSource=admin"
