apiVersion: v1
kind: Secret
metadata:
  name: admin-api-secret
  namespace: admin-api
type: Opaque
stringData:
  JWT_SECRET: "mongodb://admin:CHANGE_ME@103.165.144.81:27017/shop_dev?authSource=admin"
  MONGODB_URI: "CHANGE_ME"
