apiVersion: v1
kind: Secret
metadata:
  name: admin-api-secret
  namespace: admin-api
type: Opaque
stringData:
  JWT_SECRET: "CHANGE_ME"
  MONGODB_URI: "CHANGE_ME"
  GOOGLE_CLIENT_ID: "CHANGE_ME"
  GOOGLE_CLIENT_SECRET: "CHANGE_ME"
